version: 0.2

env:
  parameter-store:
    SAM_ARTIFACTS_BUCKET_NAME: 'SAM_ARTIFACTS_BUCKET_NAME'
phases:
  install:
    commands:
      - pip install --user aws-sam-cli
      - export PATH=$PATH:$USER_BASE_PATH/bin
      - exec "$SHELL"
  pre_build:
    commands:
      - echo "Installing dependencies - `pwd`"
      - cd hello-world && npm install
      - echo "dependencies install completed `date`"
  build:
    commands:
      - echo "Starting build `date` in `pwd`"
      - sam build
      - sam package --output-template-file package.yml --s3-bucket $SAM_ARTIFACTS_BUCKET_NAME
  post_build:
    commands:
      - cd hello-world && npm run test
      - echo "build completed on `date`"
artifacts:
  files:
    - app/**/*
    - package.yaml
  name: sam-policy-app-build
  discard-paths: yes
