version: 0.2

env:
  parameter-store:
    SAM_ARTIFACTS_BUCKET_NAME: 'SAM_ARTIFACTS_BUCKET_NAME'
phases:
  install:
    commands:
      - pip install awscli --user --upgrade
      - pip install --user aws-sam-cli
      - python -m site --user-base
  pre_build:
    commands:
      - echo "Installing dependencies - `pwd`"
      - (cd hello-world && npm install)
      - echo "dependencies install completed `date`"
  build:
    commands:
      - echo "Starting build `date` in `pwd`"
      - /root/.local/bin/sam build
      - /root/.local/bin/sam package --output-template-file package.yml --s3-bucket $SAM_ARTIFACTS_BUCKET_NAME
  post_build:
    commands:
      - cd hello-world && npm run test
      - echo "build completed on `date`"
artifacts:
  files:
    - package.yml
  name: sam-policy-app-build
  discard-paths: yes
